# ════════════════════════════════════════════
# SignBridge — pdf_generator/summary_pdf.py
# ReportLab PDF generation with meeting summary
# Color scheme: Deep navy + teal accents
# ════════════════════════════════════════════

import os
import asyncio
from datetime import datetime
from typing import Optional

from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    HRFlowable, ListFlowable, ListItem, PageBreak
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.units import cm, mm
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_JUSTIFY
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont

# ── Color Palette ─────────────────────────────
NAVY       = colors.HexColor("#0A0E1A")
DARK_CARD  = colors.HexColor("#111827")
TEAL       = colors.HexColor("#00D4FF")
PURPLE     = colors.HexColor("#7C3AED")
SUCCESS    = colors.HexColor("#10B981")
TEXT_1     = colors.HexColor("#F8FAFC")
TEXT_2     = colors.HexColor("#94A3B8")
TEXT_3     = colors.HexColor("#64748B")
WHITE      = colors.white

PDF_OUTPUT_DIR = os.getenv("PDF_OUTPUT_DIR", "./pdfs")


def _build_styles():
    base = getSampleStyleSheet()

    styles = {}

    styles["title"] = ParagraphStyle(
        "SBTitle",
        fontSize=24,
        fontName="Helvetica-Bold",
        textColor=TEAL,
        spaceAfter=4,
        alignment=TA_CENTER
    )
    styles["subtitle"] = ParagraphStyle(
        "SBSubtitle",
        fontSize=12,
        fontName="Helvetica",
        textColor=TEXT_2,
        spaceAfter=2,
        alignment=TA_CENTER
    )
    styles["section_header"] = ParagraphStyle(
        "SBSectionHeader",
        fontSize=14,
        fontName="Helvetica-Bold",
        textColor=TEAL,
        spaceBefore=14,
        spaceAfter=6,
        borderPad=4
    )
    styles["body"] = ParagraphStyle(
        "SBBody",
        fontSize=10,
        fontName="Helvetica",
        textColor=colors.HexColor("#1e293b"),
        spaceAfter=4,
        leading=15,
        alignment=TA_JUSTIFY
    )
    styles["bullet"] = ParagraphStyle(
        "SBBullet",
        fontSize=10,
        fontName="Helvetica",
        textColor=colors.HexColor("#1e293b"),
        spaceAfter=2,
        leftIndent=16,
        leading=14
    )
    styles["sign_entry"] = ParagraphStyle(
        "SBSignEntry",
        fontSize=9,
        fontName="Helvetica",
        textColor=colors.HexColor("#1e3a5f"),
        spaceAfter=2,
        leftIndent=16,
        leading=13
    )
    styles["transcript"] = ParagraphStyle(
        "SBTranscript",
        fontSize=8,
        fontName="Courier",
        textColor=colors.HexColor("#334155"),
        spaceAfter=2,
        leading=12
    )
    styles["footer"] = ParagraphStyle(
        "SBFooter",
        fontSize=8,
        fontName="Helvetica",
        textColor=TEXT_3,
        alignment=TA_CENTER
    )

    return styles


def _header_footer(canvas, doc):
    canvas.saveState()
    width, height = A4

    # Header bar
    canvas.setFillColor(NAVY)
    canvas.rect(0, height - 40, width, 40, fill=True, stroke=False)

    # Teal accent line
    canvas.setFillColor(TEAL)
    canvas.rect(0, height - 43, width, 3, fill=True, stroke=False)

    # Header text
    canvas.setFillColor(WHITE)
    canvas.setFont("Helvetica-Bold", 10)
    canvas.drawString(20, height - 28, "SignBridge — Meeting Summary")
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(TEXT_2)
    page_str = f"Page {doc.page}"
    canvas.drawRightString(width - 20, height - 28, page_str)

    # Footer
    canvas.setFillColor(TEXT_3)
    canvas.rect(0, 0, width, 30, fill=True, stroke=False)
    canvas.setFont("Helvetica", 7)
    canvas.setFillColor(WHITE)
    canvas.drawCentredString(width / 2, 12, "Generated by SignBridge AI  ·  Powered by Google Gemini  ·  Confidential")

    canvas.restoreState()


async def generate_meeting_pdf(
    meeting_id: str,
    summary: dict,
    transcript: list[dict],
    duration_seconds: int,
    user_name: str = "SignBridge User"
) -> Optional[str]:
    """
    Generate a PDF report for the meeting.
    Returns the path to the generated PDF, or None on error.
    """
    os.makedirs(PDF_OUTPUT_DIR, exist_ok=True)
    pdf_path = os.path.join(PDF_OUTPUT_DIR, f"{meeting_id}.pdf")

    loop = asyncio.get_event_loop()
    result = await loop.run_in_executor(
        None, _generate_pdf_sync,
        pdf_path, meeting_id, summary, transcript, duration_seconds, user_name
    )
    return pdf_path if result else None


def _generate_pdf_sync(pdf_path, meeting_id, summary, transcript, duration_seconds, user_name):
    try:
        doc = SimpleDocTemplate(
            pdf_path,
            pagesize=A4,
            rightMargin=2*cm,
            leftMargin=2*cm,
            topMargin=3*cm,
            bottomMargin=2*cm
        )

        styles  = _build_styles()
        story   = []
        width   = A4[0] - 4*cm

        # ── Title Block ───────────────────────
        story.append(Spacer(1, 0.3*cm))
        story.append(Paragraph("🤟 SignBridge", styles["title"]))
        story.append(Paragraph("Meeting Summary Report", styles["subtitle"]))

        date_str = datetime.now().strftime("%B %d, %Y at %I:%M %p")
        h = duration_seconds // 3600
        m = (duration_seconds % 3600) // 60
        s = duration_seconds % 60
        dur_str = f"{h}h {m}m {s}s" if h > 0 else f"{m}m {s}s"

        meta_data = [
            ["Meeting ID", meeting_id],
            ["Date & Time", date_str],
            ["Duration",   dur_str],
            ["Participant", user_name],
        ]
        meta_table = Table(meta_data, colWidths=[3*cm, width - 3*cm])
        meta_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#f1f5f9")),
            ("FONTNAME",   (0, 0), (0, -1), "Helvetica-Bold"),
            ("FONTSIZE",   (0, 0), (-1, -1), 9),
            ("TEXTCOLOR",  (0, 0), (0, -1), NAVY),
            ("TEXTCOLOR",  (1, 0), (1, -1), colors.HexColor("#1e293b")),
            ("PADDING",    (0, 0), (-1, -1), 5),
            ("GRID",       (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
            ("ROWBACKGROUNDS", (0, 0), (-1, -1), [WHITE, colors.HexColor("#f8fafc")]),
        ]))
        story.append(Spacer(1, 0.3*cm))
        story.append(meta_table)
        story.append(HRFlowable(width=width, color=TEAL, thickness=1.5, spaceAfter=6))

        # ── Section 1: Summary ────────────────
        story.append(Paragraph("📋 Meeting Summary", styles["section_header"]))
        summary_text = summary.get("summary") or "No summary generated."
        story.append(Paragraph(summary_text, styles["body"]))

        # ── Section 2: Key Points ─────────────
        key_points = summary.get("key_points", [])
        if key_points:
            story.append(Paragraph("💡 Key Discussion Points", styles["section_header"]))
            for kp in key_points:
                story.append(Paragraph(f"• {kp}", styles["bullet"]))

        # ── Section 3: Action Items ───────────
        action_items = summary.get("action_items", [])
        if action_items:
            story.append(Paragraph("✅ Action Items", styles["section_header"]))
            for ai in action_items:
                story.append(Paragraph(f"☐  {ai}", styles["bullet"]))

        # ── Section 4: Sign User Contributions ─
        sign_contribs = summary.get("sign_contributions", [])
        if sign_contribs:
            story.append(Paragraph("🤟 Sign Language User Contributions", styles["section_header"]))
            contrib_rows = []
            for i, contrib in enumerate(sign_contribs, 1):
                contrib_rows.append([f"{i}.", contrib])

            if contrib_rows:
                ct = Table([[Paragraph(r[0], styles["body"]), Paragraph(r[1], styles["sign_entry"])]
                             for r in contrib_rows],
                           colWidths=[0.5*cm, width - 0.5*cm])
                ct.setStyle(TableStyle([
                    ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#eff6ff")),
                    ("GRID",       (0, 0), (-1, -1), 0.3, colors.HexColor("#bfdbfe")),
                    ("PADDING",    (0, 0), (-1, -1), 4),
                ]))
                story.append(ct)

        # ── Section 5: Full Transcript ─────────
        story.append(PageBreak())
        story.append(Paragraph("📜 Full Meeting Transcript", styles["section_header"]))

        if transcript:
            transcript_data = [["Time", "Speaker", "Text"]]
            for entry in transcript:
                elapsed = entry.get("elapsed", 0)
                mins    = elapsed // 60
                secs    = elapsed % 60
                speaker = "Sign User" if entry.get("speaker") == "sign_user" else "Participant"
                transcript_data.append([
                    f"{mins:02d}:{secs:02d}",
                    speaker,
                    entry.get("text", "")
                ])

            tt = Table(
                transcript_data,
                colWidths=[1.5*cm, 3*cm, width - 4.5*cm],
                repeatRows=1
            )
            tt.setStyle(TableStyle([
                ("BACKGROUND",   (0, 0), (-1, 0), NAVY),
                ("TEXTCOLOR",    (0, 0), (-1, 0), WHITE),
                ("FONTNAME",     (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE",     (0, 0), (-1, -1), 7.5),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [WHITE, colors.HexColor("#f1f5f9")]),
                ("GRID",         (0, 0), (-1, -1), 0.3, colors.HexColor("#e2e8f0")),
                ("PADDING",      (0, 0), (-1, -1), 3),
                ("VALIGN",       (0, 0), (-1, -1), "TOP"),
            ]))
            story.append(tt)
        else:
            story.append(Paragraph("No transcript entries recorded.", styles["body"]))

        doc.build(story, onFirstPage=_header_footer, onLaterPages=_header_footer)
        print(f"[SignBridge PDF] Generated: {pdf_path}")
        return True

    except Exception as e:
        print(f"[SignBridge PDF] Error: {e}")
        return False
