from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRule
from reportlab.pdfgen import canvas

def add_header_footer(canvas, doc):
    canvas.saveState()
    
    # Header Background
    canvas.setFillColor(colors.HexColor("#0A0E1A"))
    canvas.rect(0, doc.height + pass_offset, doc.width + 100, 60, fill=1, stroke=0)
    
    # Footer
    canvas.setFont('Helvetica', 9)
    canvas.setFillColor(colors.HexColor("#9CA3AF"))
    page_num = canvas.getPageNumber()
    text = f"Generated by SignBridge AI • Page {page_num}"
    canvas.drawString(doc.leftMargin, doc.bottomMargin - 30, text)
    
    canvas.restoreState()

pass_offset = 70 # Global offset for header

def generate_pdf(summary_data: dict, output_path: str):
    """
    Generate a formatted PDF meeting summary using ReportLab.
    """
    doc = SimpleDocTemplate(
        output_path, 
        pagesize=letter,
        rightMargin=40, leftMargin=40,
        topMargin=80, bottomMargin=50
    )
    
    styles = getSampleStyleSheet()
    
    # Custom Styles
    styles.add(ParagraphStyle(
        name='SignBridgeTitle', 
        parent=styles['Heading1'],
        fontSize=24,
        textColor=colors.HexColor("#0A0E1A"),
        spaceAfter=15,
        fontName='Helvetica-Bold'
    ))
    
    styles.add(ParagraphStyle(
        name='SectionHeader', 
        parent=styles['Heading2'],
        fontSize=14,
        textColor=colors.HexColor("#7C3AED"),
        spaceBefore=15,
        spaceAfter=8,
        borderPadding=5,
        fontName='Helvetica-Bold'
    ))
    
    styles.add(ParagraphStyle(
        name='BodyTextCustom', 
        parent=styles['Normal'],
        fontSize=11,
        leading=16,
        textColor=colors.HexColor("#333333")
    ))
    
    styles.add(ParagraphStyle(
        name='BulletPointInfo', 
        parent=styles['Normal'],
        fontSize=11,
        leading=16,
        leftIndent=20,
        bulletIndent=10,
        textColor=colors.HexColor("#333333")
    ))
    
    styles.add(ParagraphStyle(
        name='SignUserBox', 
        parent=styles['Normal'],
        fontSize=11,
        leading=16,
        leftIndent=10,
        rightIndent=10,
        textColor=colors.HexColor("#005C7A"),
        backColor=colors.HexColor("#E5F9FD"),
        borderPadding=10,
        borderColor=colors.HexColor("#00D4FF"),
        borderWidth=1,
        borderRadius=5
    ))

    story = []

    # Title & Metadata
    story.append(Paragraph(f"SignBridge Meeting Summary", styles['SignBridgeTitle']))
    
    date_str = summary_data.get('date', 'Unknown Date').replace('T', ' ')[:16]
    duration = summary_data.get('duration', 0)
    mins = duration // 60
    secs = duration % 60
    dur_str = f"{mins}m {secs}s"
    
    meta_text = f"<b>Meeting ID:</b> {summary_data.get('meeting_id', 'N/A')} &nbsp;&nbsp;&nbsp; <b>Date:</b> {date_str} &nbsp;&nbsp;&nbsp; <b>Duration:</b> {dur_str}"
    story.append(Paragraph(meta_text, styles['Normal']))
    story.append(Spacer(1, 20))
    story.append(HRule(width="100%", color=colors.HexColor("#E5E7EB"), thickness=1))
    story.append(Spacer(1, 10))

    # Executive Summary
    story.append(Paragraph("Executive Summary", styles['SectionHeader']))
    story.append(Paragraph(summary_data.get("summary", "No summary available."), styles['BodyTextCustom']))
    
    # Key Points
    points = summary_data.get("key_points", [])
    if points:
        story.append(Paragraph("Key Discussion Points", styles['SectionHeader']))
        for pt in points:
            story.append(Paragraph(f"• {pt}", styles['BulletPointInfo']))
            story.append(Spacer(1, 3))

    # Action Items
    actions = summary_data.get("action_items", [])
    if actions:
        story.append(Paragraph("Action Items", styles['SectionHeader']))
        for action in actions:
            story.append(Paragraph(f"☐ {action}", styles['BulletPointInfo']))
            story.append(Spacer(1, 3))

    # Sign User Contributions
    story.append(Paragraph("Deaf/HoH Participant Contributions", styles['SectionHeader']))
    contribs = summary_data.get("sign_user_contributions", "No specific contributions noted.")
    story.append(Paragraph(contribs, styles['SignUserBox']))
    
    # Define page frame wrapper to add header/footer
    def on_page(canvas, doc):
        # Top bar
        canvas.saveState()
        canvas.setFillColor(colors.HexColor("#0A0E1A"))
        canvas.rect(0, doc.height + 90, doc.width + 100, 40, fill=1, stroke=0)
        
        canvas.setFillColor(colors.HexColor("#00D4FF"))
        canvas.setFont('Helvetica-Bold', 14)
        canvas.drawString(40, doc.height + 102, "SignBridge Report")
        
        # Bottom footer
        canvas.setFont('Helvetica', 9)
        canvas.setFillColor(colors.HexColor("#9CA3AF"))
        page_num = canvas.getPageNumber()
        text = f"Generated by AI Transcription & Summarization • Page {page_num}"
        canvas.drawString(40, 30, text)
        canvas.restoreState()

    # Build PDF
    doc.build(story, onFirstPage=on_page, onLaterPages=on_page)
    print(f"[PDFGenerator] Summary PDF created at {output_path}")

if __name__ == "__main__":
    # Test
    dummy_data = {
        "meeting_id": "test_123",
        "date": "2023-10-27T14:30:00Z",
        "duration": 1500,
        "summary": "The team discussed the upcoming Q4 deliverables and coordinated the launch of the new dashboard.",
        "key_points": ["Q4 targets are aggressive", "Needs more front-end QA testing"],
        "action_items": ["John to finalize QA scripts", "Jane to review UI designs"],
        "sign_user_contributions": "Provided vital feedback on the contrast ratios of the new dashboard elements and approved the accessibility framework."
    }
    generate_pdf(dummy_data, "test.pdf")
